artifact_location: file:///Users/Dmitry_Sorokin/Git/Projects/e2e-ml-with-open-source/mlflow_runs/730638874196394914
creation_time: 1731672233510
experiment_id: '730638874196394914'
last_update_time: 1731672233510
lifecycle_stage: active
name: e2e_ml_with_open_source
